
/************
* Author: Calyn Bauer, Lauren Bailey, and Issac Jarrells
* CS 225 Project
* Purpose: This header file holds the structure contaiing the random colors/letters generated by numbers_to_colors.c
* and the random numbers structure
* Previous Version March 30, 2023
*  Version 1.0 October 31, 2023
*************/
#ifndef UNTITLED_PATTERNGEN_H
#define UNTITLED_PATTERNGEN_H

#include<iostream>
#include <cstdlib>
#include <ctime>
#include "headers.h"

using namespace std;

char numbers_to_colors(int);
typedef struct random_numbers  // created random numbers structure here
{
    char num[MAX];
} RAND_NUMS;

#endif //UNTITLED_PATTERNGEN_H
