/************
* Author: Calyn Bauer, Lauren Bailey, and Issac Jarrells
* CS 225 Project
* Purpose: This header file holds the structure contaiing the random colors/letters generated by numbers_to_colors.c
* and the random numbers structure
* Previous Version March 30, 2023
*  Version 1.0 October 31, 2023
*  Version 1.1 November 18, 2023
*************/

#include "PatternGen.h"
using namespace std;

char numbers_to_colors(int);
RAND_NUMS PatternGenerator();

